CREATE DATABASE watchstore;
USE watchstore;
# Generate tables
CREATE TABLE USER_TYPE (
	UserType VARCHAR(6) NOT NULL,
    PRIMARY KEY (UserType)
);

CREATE TABLE ACCOUNT (
	Username VARCHAR(20),
    Password VARCHAR(25) NOT NULL,
    IsActived VARCHAR(3) NOT NULL,
    UserType VARCHAR(6) NOT NULL,
    PRIMARY KEY (Username)
);

CREATE TABLE CUSTOMER (
	ID INTEGER UNSIGNED AUTO_INCREMENT,
    Fullname VARCHAR(30) NOT NULL,
    PhoneNumber CHAR(10) NOT NULL,
    Street VARCHAR(50),
    Province VARCHAR (12),
    District VARCHAR(30),
    Commune VARCHAR(30),
    Username VARCHAR(20),
    CONSTRAINT UC_CUSTOMER_Username UNIQUE (Username),
    PRIMARY KEY (ID)
);

CREATE TABLE BRAND (
	BrandName VARCHAR(20),
    PRIMARY KEY (BrandName)
);

CREATE TABLE WATCH_CHAIN (
	Chain VARCHAR(20),
    PRIMARY KEY (Chain)
);

CREATE TABLE WATCH_FACE_MATERIAL (
	FaceMaterial VARCHAR(20),
    PRIMARY KEY (FaceMaterial)
);

CREATE TABLE DIAL_TYPE (
	Dial VARCHAR(20),
    PRIMARY KEY (Dial)
);

CREATE TABLE WATCH_FACE_SHAPE (
	FaceShape VARCHAR(20),
    PRIMARY KEY (FaceShape)
);

CREATE TABLE WATCH_MACHINE (
	Machine VARCHAR(20),
    PRIMARY KEY (Machine)
);

CREATE TABLE FOR_OBJECT (
	Object VARCHAR(6),
    PRIMARY KEY (Object)
);

CREATE TABLE PRODUCT (
	ID INTEGER UNSIGNED AUTO_INCREMENT,
    Title VARCHAR(20),
	BrandName VARCHAR(20),
    Chain VARCHAR(20),
    FaceMaterial VARCHAR(20),
    Dial VARCHAR(20),
    FaceShape VARCHAR(20),
    Machine VARCHAR(20),
    ForObject VARCHAR(6),
    CurrentPrice INTEGER UNSIGNED,
    HasLeft INTEGER UNSIGNED,
    CONSTRAINT UC_PRODUCT_Title UNIQUE (Title),
    PRIMARY KEY (ID)
);

CREATE TABLE LINK_IMAGE (
	ProductID INTEGER UNSIGNED,
    LinkImage VARCHAR(100) NOT NULL,
    PRIMARY KEY (ProductID, LinkImage)
);

CREATE TABLE APPOINTMENT (
	ID INTEGER UNSIGNED AUTO_INCREMENT,
    CustomerID INTEGER UNSIGNED NOT NULL,
    DateOfPayment DATETIME DEFAULT CURRENT_TIMESTAMP,
    Quantity TINYINT UNSIGNED,
    TotalPrice INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE IN_CART (
	AppointmentID INTEGER UNSIGNED,
    ProductID INTEGER UNSIGNED,
    Price INTEGER,
    PRIMARY KEY (AppointmentID, ProductID)
);

#Generate constraints
# ACCOUNT TABLE
ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_USER_TYPE
FOREIGN KEY (UserType) REFERENCES USER_TYPE(UserType);

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_ACCOUNT_IsActived
CHECK (IsActived='YES' OR IsActived='NO');

ALTER TABLE ACCOUNT
ALTER IsActived SET DEFAULT 'YES';

# CUSTOMER TABLE
ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ACCOUNT
FOREIGN KEY (Username) REFERENCES ACCOUNT(Username);

# PRODUCT TABLE
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_BRAND
FOREIGN KEY (BrandName) REFERENCES BRAND(BrandName);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_CHAIN
FOREIGN KEY (Chain) REFERENCES WATCH_CHAIN(Chain);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_FACE_MATERIAL
FOREIGN KEY (FaceMaterial) REFERENCES WATCH_FACE_MATERIAL(FaceMaterial);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_DIAL_TYPE
FOREIGN KEY (Dial) REFERENCES DIAL_TYPE(Dial);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_FACE_SHAPE
FOREIGN KEY (FaceShape) REFERENCES WATCH_FACE_SHAPE(FaceShape);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_MACHINE
FOREIGN KEY (Machine) REFERENCES WATCH_MACHINE(Machine);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_FOR_OBJECT
FOREIGN KEY (ForObject) REFERENCES FOR_OBJECT(Object);

# LINK_IMAGE TABLE
ALTER TABLE LINK_IMAGE
ADD CONSTRAINT FK_LINK_IMAGE_PRODUCT
FOREIGN KEY (ProductID) REFERENCES PRODUCT(ID);

# APPOINTMENT TABLE
ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_CUSTOMER
FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(ID);

# IN_CART TABLE
ALTER TABLE IN_CART
ADD CONSTRAINT FK_IN_CART_APPOINTMENT
FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT(ID);

ALTER TABLE IN_CART
ADD CONSTRAINT FK_IN_CART_PRODUCT
FOREIGN KEY (ProductID) REFERENCES PRODUCT(ID);