CREATE DATABASE watchstore;
USE watchstore;
# Generate tables
CREATE TABLE USER_TYPE (
	user_type VARCHAR(6) NOT NULL,
    PRIMARY KEY (user_type)
);

CREATE TABLE ACCOUNT (
	username VARCHAR(20),
    password VARCHAR(25) NOT NULL,
    is_actived VARCHAR(3) NOT NULL,
    user_type VARCHAR(6) NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE CUSTOMER (
	id INTEGER UNSIGNED AUTO_INCREMENT,
    full_name VARCHAR(30) NOT NULL,
    phone_number CHAR(10) NOT NULL,
    street VARCHAR(50),
    province VARCHAR (12),
    district VARCHAR(30),
    commune VARCHAR(30),
    username VARCHAR(20),
    CONSTRAINT UC_CUSTOMER_Username UNIQUE (username),
    PRIMARY KEY (id)
);

CREATE TABLE BRAND (
	brand_name VARCHAR(20),
    PRIMARY KEY (brand_name)
);

CREATE TABLE WATCH_CHAIN (
	chain VARCHAR(20),
    PRIMARY KEY (chain)
);

CREATE TABLE WATCH_FACE_MATERIAL (
	face_material VARCHAR(20),
    PRIMARY KEY (face_material)
);

CREATE TABLE DIAL_TYPE (
	dial VARCHAR(20),
    PRIMARY KEY (dial)
);

CREATE TABLE WATCH_FACE_SHAPE (
	face_shape VARCHAR(20),
    PRIMARY KEY (face_shape)
);

CREATE TABLE WATCH_MACHINE (
	machine VARCHAR(20),
    PRIMARY KEY (machine)
);

CREATE TABLE FOR_OBJECT (
	object VARCHAR(6),
    PRIMARY KEY (object)
);

CREATE TABLE PRODUCT (
	id INTEGER UNSIGNED AUTO_INCREMENT,
    title VARCHAR(20),
	brand_name VARCHAR(20),
    chain VARCHAR(20),
    face_material VARCHAR(20),
    dial VARCHAR(20),
    face_shape VARCHAR(20),
    machine VARCHAR(20),
    for_object VARCHAR(6),
    current_price INTEGER UNSIGNED,
    has_left INTEGER UNSIGNED,
    CONSTRAINT UC_PRODUCT_Title UNIQUE (title),
    PRIMARY KEY (id)
);

CREATE TABLE LINK_IMAGE (
	product_id INTEGER UNSIGNED,
    link_image VARCHAR(100) NOT NULL,
    PRIMARY KEY (link_image)
);

CREATE TABLE APPOINTMENT (
	id INTEGER UNSIGNED AUTO_INCREMENT,
    customer_id INTEGER UNSIGNED NOT NULL,
    date_of_payment DATETIME DEFAULT CURRENT_TIMESTAMP,
    quantity TINYINT UNSIGNED,
    total_price INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE IN_CART (
	appointment_id INTEGER UNSIGNED,
    product_id INTEGER UNSIGNED,
    price INTEGER,
    PRIMARY KEY (appointment_id, product_id)
);

#Generate constraints
# ACCOUNT TABLE
ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_USER_TYPE
FOREIGN KEY (user_type) REFERENCES USER_TYPE(user_type);

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_ACCOUNT_IsActived
CHECK (is_actived='YES' OR is_actived='NO');

ALTER TABLE ACCOUNT
ALTER is_actived SET DEFAULT 'YES';

# CUSTOMER TABLE
ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ACCOUNT
FOREIGN KEY (username) REFERENCES ACCOUNT(username);

# PRODUCT TABLE
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_BRAND
FOREIGN KEY (brand_name) REFERENCES BRAND(brand_name);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_CHAIN
FOREIGN KEY (chain) REFERENCES WATCH_CHAIN(chain);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_FACE_MATERIAL
FOREIGN KEY (face_material) REFERENCES WATCH_FACE_MATERIAL(face_material);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_DIAL_TYPE
FOREIGN KEY (dial) REFERENCES DIAL_TYPE(dial);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_FACE_SHAPE
FOREIGN KEY (face_shape) REFERENCES WATCH_FACE_SHAPE(face_shape);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_WATCH_MACHINE
FOREIGN KEY (machine) REFERENCES WATCH_MACHINE(machine);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_FOR_OBJECT
FOREIGN KEY (for_object) REFERENCES FOR_OBJECT(object);

# LINK_IMAGE TABLE
ALTER TABLE LINK_IMAGE
ADD CONSTRAINT FK_LINK_IMAGE_PRODUCT
FOREIGN KEY (product_id) REFERENCES PRODUCT(id);

# APPOINTMENT TABLE
ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_CUSTOMER
FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id);

# IN_CART TABLE
ALTER TABLE IN_CART
ADD CONSTRAINT FK_IN_CART_APPOINTMENT
FOREIGN KEY (appointment_id) REFERENCES APPOINTMENT(id);

ALTER TABLE IN_CART
ADD CONSTRAINT FK_IN_CART_PRODUCT
FOREIGN KEY (product_id) REFERENCES PRODUCT(id);